Feature/nav header
FrameworkDesign/john-a-stephens pull request #13
Opened 2022-07-22 13:12 UTC by sattyframework

Desktop nav bar
![Screenshot](https://user-images.githubusercontent.com/109515230/180446176-53e0744a-89dd-4cfd-8b9d-6b85fa5dce9a.png)

Child on nav hover
![DesktopNav](https://user-images.githubusercontent.com/109515230/180446143-1d519e30-abc4-4c12-8ce6-9603792ac4ec.png)

2022-07-22 13:21 UTC, paulweareframework approved these changes

2022-07-25 09:16 UTC, FrameworkJames requested changes

2022-07-25 09:16 UTC, FrameworkJames commented on resources/css/components/site/header.css
> +.desktop-nav li .child-nav:hover {
Try to use just classes to target css. It helps with layout flexibility and style specificity in tailwind as an element will take precedence over tailwind utilities.

This can also be achieved quite nicely with the `group and group-hover:*` helpers in TW.

2022-07-25 09:16 UTC, FrameworkJames commented on resources/views/site/_header.antlers.html
> +<header class="site-header container pt-60 pb-150">
is this padding for both desktop and mobile? Seems a lot for mobile.

2022-07-25 09:16 UTC, FrameworkJames commented on resources/views/site/_primary-nav.antlers.html
> +  <ul class="desktop-nav flex items-center">
Using BEM this would be `site-primaryNav__list` or something similar.

2022-07-25 09:16 UTC, FrameworkJames commented on resources/views/site/_primary-nav.antlers.html
> +    <a href="/search">{{ svg src="search-icon" }}</a>
I would add an `aria-label` to this describing it's function.

2022-07-25 09:16 UTC, FrameworkJames commented on resources/views/site/_primary-nav.antlers.html
> +    <span class="px-30">{{ svg src="small-vertical-rule" }}</span>
I would recommend doing this in CSS. cutting down on SVGs where possible is always good for perf.

2022-07-25 09:57 UTC, sattyframework commented on resources/css/components/site/header.css
> +.desktop-nav li .child-nav:hover {
Oh great, I have not come across that before. Good to know :)

2022-07-26 09:47 UTC, FrameworkJames approved these changes

2022-07-26 10:07 UTC, merged