featured products section
FrameworkDesign/john-a-stephens pull request #19
Opened 2022-07-27 15:44 UTC by sattyframework

Feature products section. Created taxonomies for the different product categories. 
Clicking on a link on the left loads content on the right. 
**Todo:**  need to extract the js

Desktop
![FeaturedProductsDesktop](https://user-images.githubusercontent.com/109515230/181289967-af9f6a9a-c023-431a-aac6-5984d2d7096b.png)

Mobile
<img src="https://user-images.githubusercontent.com/109515230/181290660-72250a02-8f53-4b26-bf35-787ae4b59221.png" width="300px">

2022-07-31 15:08 UTC, sattyframework commented on resources/css/components/category-tabs.css
> +  .categoryLinks.active {
I couldn't figure out a way to trigger this in tailwind,  but if there is a better way then I am happy to change it.

2022-08-01 13:38 UTC, Dunsters99 requested changes

2022-08-01 13:38 UTC, Dunsters99 commented on resources/js/main.js
> +      new CategoryTabs(el, el.id)
you could access the id once inside the JS class

2022-08-01 13:38 UTC, Dunsters99 commented on resources/js/site/categoryTabs.js
> +    if (isNull(el)) return
I'd also check if the id is null

2022-08-01 13:38 UTC, Dunsters99 commented on resources/js/site/categoryTabs.js
> +    tablinks = document.getElementsByClassName('categoryLinks')
is there anyway to have already queried this element before this point?

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +        <button id="{{slug}}" class="categoryLinks text-slate-dark/30 text-[22px] xl:text-[28px] block default-transition py-10 cursor-pointer hover:text-slate-dark origin-left hover:scale-150 {{ if
I'd keep the same naming structure here as the parent component e.g.
```suggestion
        <button id="{{slug}}" class="global-categoryTabs__links text-slate-dark/30 text-[22px] xl:text-[28px] block default-transition py-10 cursor-pointer hover:text-slate-dark origin-left hover:scale-150 {{ if first }}active{{/if}}">
```

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +      <h5 class="heading-xs text-mustard">Our Products</h5>
Any way this can be content managed?

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +    <div class="w-full xl:w-6/12 column flex flex-col justify-center">
is `flex flex-col` required here? `display: block` will do the same thing and it's a default style for a `div` tag

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +        <div id="{{slug}}-content" class="categoryContent relative {{ if first }}active block{{else}}hidden{{/if}}">
same RE the class name

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +          <h3 class="heading py-10 text-slate-dark">{{title}}</h3>
if checks

2022-08-01 13:38 UTC, Dunsters99 commented on resources/views/global/_categories-tabs.antlers.html
> +          <a href="/contact">
I wouldn't hard code any url's, this link may need to change to `/contact-us` and that would be easily changed in the CMS

2022-08-01 13:39 UTC, Dunsters99 commented
RE "the tab change is not animated, will look at adding this in later down the line."

I'd still have a go at animating this component while you're on it

2022-08-01 14:11 UTC, sattyframework commented on resources/views/global/_categories-tabs.antlers.html
> +    <div class="w-full xl:w-6/12 column flex flex-col justify-center">
Hmm I believe I was trying to align the div vertically in the centre. Although I can probably use height and margin:auto instead of flex if thats better? 

![8214DE62-2EA0-4F3B-AE8C-4929AF495394](https://user-images.githubusercontent.com/109515230/182166130-0cdafebb-5e03-4665-bd0f-cf8bf2a8630b.jpeg).

2022-08-02 08:38 UTC, paulweareframework approved these changes

2022-08-02 09:50 UTC, Dunsters99 approved these changes

2022-08-02 09:54 UTC, merged