Feature/latest news slider
FrameworkDesign/john-a-stephens pull request #22
Opened 2022-07-29 11:05 UTC by sattyframework

- Installed swiper 
- created global slider javascript 
- added tertiary button style (wasnt included in dev handover but is used several times)

**Desktop**
![DesktopNewsSlider](https://user-images.githubusercontent.com/109515230/181746194-66a31439-1bde-4e97-a0cc-c6b8169d5d2f.png)

**Mobile**
<img src="https://user-images.githubusercontent.com/109515230/181746205-1d5b3252-1903-4a44-af13-b3f0ef53228e.png" width="300px">

2022-07-29 11:47 UTC, Dunsters99 requested changes

2022-07-29 11:47 UTC, Dunsters99 commented on public/svg/arrow-left.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="20px" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
if you already have an arrow svg, you could use `-scale-x-100` to flip it

2022-07-29 11:47 UTC, Dunsters99 commented on resources/js/site/global-slider.js
> +        nextEl: '.swiper-arrow-right',
I'd name the swiper navigation buttons more specific to the component

2022-07-29 11:47 UTC, Dunsters99 commented on resources/js/site/global-slider.js
> +      loop: false,
I think most of these props are default fyi

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/_latest-news-slider.antlers.html
> +<div class="global-news-slider relative py-90 bg-concrete">
Our naming structure ould be something like this...
```suggestion
<div class="global-newsSlider relative py-90 bg-concrete">
```

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/_latest-news-slider.antlers.html
> +<div class="global-news-slider relative py-90 bg-concrete">
`py-90` on mobile as well?

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/_latest-news-slider.antlers.html
> +  <div class="swiper overflow-visible container">
I'd wrap the swiper element in a `div` with container on, rather than have `.`container` on the swiper element

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/_latest-news-slider.antlers.html
> +        {{ partial:global/btn/arrow-left class="btn-arrow--garden btn-arrow--round swiper-arrow-left"}}
again you could use `.-scale-x-100`, rather than create a whole new component

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/_latest-news-slider.antlers.html
> +          <div class="column swiper-slide w-full md:w-1/2 xl:w-1/3 relative">
I know it doesn't make any style changes, however we like to define our widths as a fraction of 12 (columns in the grid), when we can, so we can quickly understand how the layout of the component is.
```suggestion
          <div class="column swiper-slide w-full md:w-6/12 xl:w-4/12 relative">
```

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/global/btn/_arrow-left.antlers.html
> +<button class="btn-arrow {{class}}">{{ svg src="arrow-left" }}</button>
see comments above

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/site/news/_news-card.antlers.html
> +  {{ partial:helpers/media :media="featured_media.0" class="w-full h-[540px] object-cover object-center" }}
you could use `.aspect-[*ratio*]` rather than defining a specific height

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/site/news/_news-card.antlers.html
> +      <p class="font-bold text-[18px]">{{title}}</p>
is there no typography style that can be used here?

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/site/news/_news-card.antlers.html
> +      <p class="text-concrete">{{excerpt}}</p>
if checks

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/site/news/_news-card.antlers.html
> +  <div class="absolute bottom-0 w-full bg-gradient-to-t from-slate-dark min-h-[50%]">
make sure to define a `.to-*colour*`, some browsers will break without a from/to value

2022-07-29 11:47 UTC, Dunsters99 commented on resources/views/site/news/_news-card.antlers.html
> +      <div class="w-full p-25 hidden group-hover:flex justify-between items-start">
is there a way that we can animate this element? rather than go from `display: none;` -> `display: flex;` ?

2022-07-29 13:48 UTC, sattyframework commented on resources/views/global/_latest-news-slider.antlers.html
> +<div class="global-news-slider relative py-90 bg-concrete">
That's what the designs show, but happy to change it if you think its too much

2022-07-29 14:11 UTC, sattyframework commented on resources/views/site/news/_news-card.antlers.html
> +      <p class="font-bold text-[18px]">{{title}}</p>
Yes sorry, I have applied featured-copy font now.

2022-07-29 14:33 UTC, sattyframework commented on resources/views/site/news/_news-card.antlers.html
> +      <div class="w-full p-25 hidden group-hover:flex justify-between items-start">
I have added an animation for the green background to slide up. for some reason the default transition was not working

2022-08-01 14:00 UTC, Dunsters99 approved these changes

2022-08-01 14:00 UTC, Dunsters99 commented on resources/js/site/global-news-slider.js
> +        nextEl: '.news-slider-arrow-right',
```suggestion
        nextEl: '.news-slider__next',
```

2022-08-01 15:07 UTC, merged