Feature/about image content
FrameworkDesign/john-a-stephens pull request #50
Opened 2022-08-15 09:19 UTC by sattyframework

The about page has multiple image content sections so I had to make a couple amends to the image-text component to make it reusable: 
- use content.'data' in `_text-content.antlers.html` file instead of calling on the field directly
- rename the text bard field from 'content' -> 'body'
- added a line graphic option 
- added an option for the colour block position. It is mainly positioned on the bottom on most pages but is on the top on some. 

![image](https://user-images.githubusercontent.com/109515230/184546180-49fb8923-e3fb-4a5d-b314-ecfa8c273934.png)

2022-08-15 10:50 UTC, FrameworkJames requested changes

2022-08-15 10:50 UTC, FrameworkJames commented on resources/views/about/_brand-message.antlers.html
>          <div class="w-full xl:w-10/12 xl:ml-50 xl-max:mt-10">
for the `w-10/12` to be correct it will need row/column being added. Otherwise it will calculate it incorrectly.

2022-08-16 09:05 UTC, paulweareframework approved these changes

2022-08-17 09:58 UTC, FrameworkJames approved these changes

2022-08-17 10:07 UTC, merged