Feature/search page
FrameworkDesign/john-a-stephens pull request #55
Opened 2022-08-16 11:05 UTC by sattyframework

Search index includes: product categories, services and news articles

Default search page 
![image](https://user-images.githubusercontent.com/109515230/184863302-a8c2e997-0aae-4605-a3fa-e8cd172c3682.png)

Found Results 
![image](https://user-images.githubusercontent.com/109515230/184863829-eb69729b-7b9e-45db-bde9-2a06c5796ace.png)

2022-08-16 11:07 UTC, sattyframework commented on resources/views/search/_results.antlers.html
> +              <a {{ if taxonomy == 'product_categories' }} href="/products/{{ slug }}" {{ else }} href="{{url}}" {{ /if}}>
The taxonomy uses a custom route

2022-08-22 10:46 UTC, FrameworkJames requested changes

2022-08-22 10:46 UTC, FrameworkJames commented on resources/views/search/_results.antlers.html
> +<div>
This wrapping div seems unneeded.

2022-08-22 10:46 UTC, FrameworkJames commented on resources/views/search/_results.antlers.html
> +                  <p class="copy pt-30">{{excerpt}}</p>
I would line-clamp this excerpt.

2022-08-22 10:46 UTC, FrameworkJames commented on resources/views/search/_results.antlers.html
> +                  <button class="btn-arrow btn-arrow--mustard ml-70 p-15">
You could keep the `a` tag here and use `btn-cover` to expand the link across the card.

2022-08-24 09:20 UTC, FrameworkJames approved these changes

2022-08-24 09:32 UTC, merged