create site map links
FrameworkDesign/john-a-stephens pull request #59
Opened 2022-08-17 16:35 UTC by sattyframework

User can select entries from product categories and services. They can also select an existing nav or create a new one just for the explore menu. 

![image](https://user-images.githubusercontent.com/109515230/185194168-5b20df2d-58f2-4bcf-a264-698a01e5d52c.png)

<img src="https://user-images.githubusercontent.com/109515230/185194247-b319da77-88c8-42a7-9a9a-21ed4cb7b1de.png" width="300px">

2022-08-22 10:20 UTC, FrameworkJames approved these changes

2022-08-22 10:23 UTC, FrameworkJames requested changes

2022-08-22 10:23 UTC, FrameworkJames commented on resources/views/sitemap/_sitelinks.antlers.html
> +        <li><a class="block copy pb-10 hover:text-sage-dark default-transition xl-max:mr-10" href="/products/{{slug}}">{{ title }}</a></li>
I would create named routes for these if they are going to be managed through `routes/web`. like `product_category.show` etc.

2022-08-22 10:23 UTC, FrameworkJames commented on resources/views/sitemap/_sitelinks.antlers.html
> +        <li><a class="block copy pb-10 hover:text-sage-dark default-transition" href="{{url}}">{{ title }}</a></li>
Same here for routes.

2022-08-22 13:57 UTC, sattyframework commented on resources/views/sitemap/_sitelinks.antlers.html
> +        <li><a class="block copy pb-10 hover:text-sage-dark default-transition" href="{{url}}">{{ title }}</a></li>
do I still need to do this for services, which is a collection and the url is already defined in statamic?

2022-08-24 09:08 UTC, FrameworkJames approved these changes

2022-08-24 09:32 UTC, merged