Feature/google maps
FrameworkDesign/john-a-stephens pull request #63
Opened 2022-08-19 11:15 UTC by sattyframework

- updated vue dependencies and added in google maps api key 
- created a collection of locations in statamic and a controller to fetch them 
- use vue store to get locations and pass to google maps vue component
- the list on the left opens the infowindow on the right
- created a find us page with various repeated sections 

**NOTE:** the layout of the map looks a little different to the designs as the list on the left was over-laying on top of the map, which would affect the center point and potentially hide it.  

![Find-UsDesktop](https://user-images.githubusercontent.com/109515230/185605784-8f6ac06b-c90b-4863-917a-8a60758d79d3.png)

<img src="https://user-images.githubusercontent.com/109515230/185605793-814392e2-5321-4ffa-8762-ce4c81997ca8.png" width="300px">

2022-08-22 10:15 UTC, FrameworkJames approved these changes

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/card.vue
> +          <span v-if="location.address_line_one"
I would wrap this in an `address` html tag rather than a `p` and also wrap the entire thing in an article as it works as a standalone piece of content. Good work on here though

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/card.vue
> +        <p v-if="location.email" class="pb-20 lg:pb-10">
Wrap in an A tag and add `mailto:` here.

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/card.vue
> +        <p v-if="location.fax_number" class="pb-20 lg:pb-10">
Wrap in an `a` tag and add `tel:`

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/card.vue
> +        <p v-if="location.phone_number" class="pb-20 lg:pb-10">
Wrap in an `a` tag and add `tel:`

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/card.vue
> +        v-if="location.site_image"
Need to work out how to put responsive images in here. This is fine for now though.

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/info-window.vue
> +      <h5 class="heading-xs text-[15px] font-bold pb-10" v-if="location.title">
Try to always use margin where possible for spacing elements out from each other.

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/list.vue
> +      <div v-for="(location, index) in locations" :key="index" class="py-40">
`<ul>` -> `<li>`  would be semantically bettwe.

2022-08-22 10:15 UTC, FrameworkJames commented on resources/js/components/global/locations/list.vue
> +        <div v-html="content.body"></div>
This won't inherit the correct wysiwyg styles unless you add `v-html` to the `.wysiwyg` div.

2022-08-22 10:16 UTC, FrameworkJames requested changes

2022-08-22 10:16 UTC, FrameworkJames commented on app/Http/Controllers/LocationsController.php
> +namespace App\Http\Controllers;
Note for PR. Ignore

2022-08-22 15:53 UTC, sattyframework commented on app/Http/Controllers/LocationsController.php
> +namespace App\Http\Controllers;
Not sure what you meant here?

2022-08-24 09:03 UTC, FrameworkJames approved these changes

2022-08-24 09:34 UTC, merged