Bugfix/folder structure
FrameworkDesign/john-a-stephens pull request #9
Opened 2022-07-21 15:39 UTC by sattyframework

re-structured button styles so each styles is its own variant 
created the block button as a partial and pass in the variant classes

2022-07-21 15:41 UTC, paulweareframework approved these changes

2022-07-22 09:42 UTC, Dunsters99 requested changes

2022-07-22 09:42 UTC, Dunsters99 commented on resources/css/components/btn/btn-arrow.css
> +    @apply text-slate-dark bg-mustard disabled:bg-stone disabled:text-paleMint;
is there a hover state for this button?

2022-07-22 09:42 UTC, Dunsters99 commented on resources/css/components/btn/btn-arrow.css
> +    @apply inline-flex justify-center p-20 default-transition;
if you want to centre elements inside, I'd add `items-center` as well

2022-07-22 09:42 UTC, Dunsters99 commented on resources/css/components/btn/btn-block.css
> +    @apply relative inline-flex justify-center uppercase font-neurial text-[12px] tracking-[0.12em] py-20 px-25  default-transition;
extra space at the end of the class list

2022-07-22 09:42 UTC, Dunsters99 commented on resources/css/components/btn/btn-block.css
> +  .btn-block-bg--garden {
I think the class naming structure here would be `.btn-block--garden` then the element `.btn-block__bg` would get the classes

2022-07-22 09:42 UTC, Dunsters99 commented on resources/css/components/btn/btn-block.css
> +  .btn-block-bg--white {
same here

2022-07-22 09:42 UTC, Dunsters99 commented on resources/views/home.antlers.html
> +  {{partial:global/btn/block class="btn-block--white" inner_class="btn-block-bg--white" label="Secondary Button"}}
I'm not sure I understand how/why the `inner_class` prop is used

2022-07-22 09:58 UTC, sattyframework commented on resources/css/components/btn/btn-arrow.css
> +    @apply text-slate-dark bg-mustard disabled:bg-stone disabled:text-paleMint;
There is, it's an animation where the arrow goes right continuously. I left it for now as I didn't want to spend too much time on setting up.   
<img src="https://user-images.githubusercontent.com/109515230/180415163-89882199-63d2-488a-89e6-be37e11fcfb5.png" width="300" >

2022-07-22 10:09 UTC, sattyframework commented on resources/views/home.antlers.html
> +  {{partial:global/btn/block class="btn-block--white" inner_class="btn-block-bg--white" label="Secondary Button"}}
Removed

2022-07-22 10:45 UTC, sattyframework commented on resources/css/components/btn/btn-arrow.css
> +    @apply text-slate-dark bg-mustard disabled:bg-stone disabled:text-paleMint;
Nevermind the last comment, I've attempted the animation

2022-07-26 09:26 UTC, Dunsters99 approved these changes

2022-07-26 09:40 UTC, merged